HuskyBot_/Models/ErrorViewModel.cs
namespace HuskyBot_.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HuskyBot_/Models/IndexViewModel.cs
namespace HuskyBot_.Models
{
    public class IndexViewModel
    {
        public IEnumerable<LocationModel> Locations { get; set; }
        public IEnumerable<UserModel> Users { get; set; }
    }
}

HuskyBot_/Models/LocationModel.cs
using System.ComponentModel.DataAnnotations;
using Telegram.Bot.Types;

namespace HuskyBot_.Models
{
    public class LocationModel 
    {

        public int Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public  long UserId { get; set; }


        public string? Username { get; set; }


    }



}

HuskyBot_/Models/UserModel.cs
using Newtonsoft.Json;
using Telegram.Bot.Types;

namespace HuskyBot_.Models
{
    public class UserModel 
    {

        public long Id { get; set; }


        public bool IsBot { get; set; }

        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? Username { get; set; }

    }
}

HuskyBot_/Controllers/BotController.cs
using HuskyBot_.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Telegram.Bot;
using Telegram.Bot.Types;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;


namespace HuskyBot_.Controllers
{
    [ApiController]
    [Route("/")]
    public class BotController : Controller
    {


        public ApplicationContext db { get; set; }
        public BotController(ApplicationContext context)
        {

            db = context;
        }


        private TelegramBotClient bot = Bot.GetTelegramBot();
        private UpdateDistributor<CommandExecutor> updateDistributor = new UpdateDistributor<CommandExecutor>();


        [HttpPost]
        public async void Post(Telegram.Bot.Types.Update update)
        {




            if (update.Message == null) //и такое тоже бывает, делаем проверку
                return;


            

            await updateDistributor.GetUpdate(update, db);

            //TelegramBotClient Client = Bot.GetTelegramBot();
            //
            //Location loc = update.Message.Location;
            //
            //db.Locations.Add(new Models.LocationModel() { UserId = 000, Latitude = loc.Latitude, Longitude /=/ loc.Longitude });
            //await db.SaveChangesAsync();
            //long chatId = update.Message.Chat.Id;
            //
            //await Client.SendTextMessageAsync(chatId, $"{loc.Latitude} {loc.Longitude}");


        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            return View(await db.Locations.ToListAsync());
        }




        [HttpPost("/Bot/Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
        LocationModel location = await db.Locations.FirstOrDefaultAsync(p => p.Id == id);
                if (location != null)
                {
                    db.Locations.Remove(location);
                    await db.SaveChangesAsync();
                    

           TelegramBotClient Client = Bot.GetTelegramBot();

        long chatId = location.UserId;

        await Client.SendTextMessageAsync(chatId, $"{location.Latitude} {location.Longitude} Удалена");
                    return RedirectToAction("Get");
                }



            }
            return NotFound();
        }

    }
}

HuskyBot_/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HuskyBot_.Controllers
{

    public class HomeController
        : Controller
    {
        ApplicationContext db;
        public HomeController(ApplicationContext context)
        {
            db = context;
        }

        public ActionResult Index()
        {

            return View();
        }


    }


}

HuskyBot_/Views/Bot/Get.cshtml
@model IEnumerable<LocationModel>

<h2>Локации</h2>

<table class="table">
    <tr><th>Id</th><th>Х</th><th>У</th> <th>Пользователь</th> <th></th> <th></th> <th></th> </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Latitude</td>
            <td>@item.Longitude</td>

            <td>@item.Username</td>
            <td>@item.UserId</td>
            @{
                string s = $"https://yandex.ru/maps/54/yekaterinburg/?ll={item.Longitude}%2C{item.Latitude}&z=18"; }

            <td> <a href=@s> На карте</a>  </td>
            <td>
            <form asp-controller="Bot" asp-action="Delete" method="post" asp-route-id="@item.Id">
                <input type="submit" value="Удалить" />
            </form>
            </td>

        </tr>
    }
</table>


@*
<table class="table">
    <tr><th>Id</th><th>Х</th><th>У</th> <th>Пользователь</th></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.</td>
        </tr>
    }
</table>
*@

HuskyBot_/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

HuskyBot_/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HuskyBot_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HuskyBot_.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HuskyBot_</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HuskyBot_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>